services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: vuln_triage
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - vuln_triage_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/vuln_triage
    depends_on:
      - db
    networks:
      - vuln_triage_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://100.93.112.98:8000
    ports:
      - "5174:80"
    networks:
      - vuln_triage_network

  juice-shop:
    image: bkimminich/juice-shop
    ports:
      - "3000:3000"
    networks:
      - vuln_triage_network

volumes:
  postgres_data:

networks:
  vuln_triage_network:
    driver: bridge
