# Generated by Django 6.0.3 on 2026-03-09 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnalysisResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "validation_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("TRUE_POSITIVE", "True Positive"),
                            ("FALSE_POSITIVE", "False Positive"),
                            ("INCONCLUSIVE", "Inconclusive"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CRITICAL", "Critical"),
                            ("HIGH", "High"),
                            ("MEDIUM", "Medium"),
                            ("LOW", "Low"),
                            ("INFO", "Informational"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("confidence_score", models.FloatField(blank=True, null=True)),
                ("static_analysis_result", models.JSONField(blank=True, null=True)),
                ("dynamic_analysis_result", models.JSONField(blank=True, null=True)),
                ("agent_reasoning", models.TextField(blank=True, null=True)),
                (
                    "llm_model_used",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("total_tokens", models.IntegerField(blank=True, null=True)),
                ("analysis_duration", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "analysis_results",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VulnerabilityReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("SQL_INJECTION", "SQL Injection"),
                            ("XSS", "Cross-Site Scripting"),
                            ("PATH_TRAVERSAL", "Path Traversal"),
                            ("CSRF", "Cross-Site Request Forgery"),
                            ("IDOR", "Insecure Direct Object Reference"),
                        ],
                        max_length=50,
                    ),
                ),
                ("endpoint", models.CharField(max_length=500)),
                ("method", models.CharField(default="GET", max_length=10)),
                ("parameter", models.CharField(blank=True, max_length=200, null=True)),
                ("payload", models.TextField(blank=True, null=True)),
                ("description", models.TextField()),
                ("target_url", models.URLField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "vulnerability_reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agent_type",
                    models.CharField(
                        choices=[
                            ("PARSER", "Parser Agent"),
                            ("STATIC_ANALYZER", "Static Analyzer Agent"),
                            ("DYNAMIC_VALIDATOR", "Dynamic Validator Agent"),
                            ("TRIAGE", "Triage Agent"),
                        ],
                        max_length=50,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("success", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("input_data", models.JSONField(blank=True, null=True)),
                ("output_data", models.JSONField(blank=True, null=True)),
                ("llm_prompt", models.TextField(blank=True, null=True)),
                ("llm_response", models.TextField(blank=True, null=True)),
                ("tokens_used", models.IntegerField(blank=True, null=True)),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_executions",
                        to="vulnerabilities.analysisresult",
                    ),
                ),
            ],
            options={
                "db_table": "agent_executions",
                "ordering": ["started_at"],
            },
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="report",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analysis",
                to="vulnerabilities.vulnerabilityreport",
            ),
        ),
    ]
